[package]
name = "gpui-qrcode"
description = "A QR code generator and renderer for gpui"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
gpui = "0.2.2"
qrcode = "0.14.1"
thiserror = "2.0.17"
